import Head from 'next/head';
import styles from '../styles/Home.module.css'
import { Box, Heading ,Text,} from '@chakra-ui/react'
const About = ()=>{
    return(
        <>
         <Head>
        <title>Digital marketing | about</title>
        <meta name="Schoollog digital marketing" content="Generated by schoollog digital marketing" />
      </Head>
        <Box className={styles.about}>
              <Heading>About</Heading>
              <Text>
                In development, expressing stylesheets this way allows your styles to be hot reloaded as you edit them—meaning you can keep application state.In production, all CSS files will be automatically concatenated into a single minified .css file.
             </Text>
             <Text>
                In development, expressing stylesheets this way allows your styles to be hot reloaded as you edit them—meaning you can keep application state.In production, all CSS files will be automatically concatenated into a single minified .css file.
             </Text>
        </Box>
        </>
    );
}
export default About;