import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import CarouselSlide from '../components/CarouselSlide'

export default function Home() {
  return (
    <Box 
    // className={styles.container}
    >
      <Head>
        <title>EV PRINTING</title>
        <meta name="EV PRINTING" content="Generated by schoollog" />
      </Head>
       <Navbar /> 
       <CarouselSlide/>
       <Footer/>
    </Box>
  )
}

