import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import AboutUs from '../components/AboutUs'
import ChooseUs from '../components/ChooseUs'
import ContactUs from '../components/ContactUs'
import Navbar from '../components/Navbar'
import Offerings from '../components/Offerings'
import Services from '../components/Services'

export default function Home() {
  return (
    <Box
    >
      <Head>
        <title>IVY PRINTING</title>
        <meta name="IVY PRINTING" content="Generated by schoollog" />
      </Head>
      <Navbar />
      <AboutUs />
      <Services />
      <Offerings />
      <ChooseUs />
      <ContactUs />
    </Box>
  )
}

